# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ff75952926eb5e61b17d04a3aab14b4cc6f86d589f257e1d79be34ca5d7d5ed3c40f896473e7bebc82654937fa7d6398238084eae3e169333c2eb288da578bd

test:
  secret_key_base: a671eb3fdc2a533f4df632e9b13804401f97bf8d34a1361352ec4915c5224a77509befc09e8551dbca882b19efb0e5c3a41557d65499f42ed831c6914dbc754a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
